default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cinco_estrelas_development

test:
  <<: *default
  database: cinco_estrelas_test

production:
  <<: *default
  database: cinco_estrelas_production
  username: cinco_estrelas
  password: <%= ENV['MULTIVAGAS_DATABASE_PASSWORD'] %>
